version: '3.3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  web-page:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.backend=web-page
      - traefik.frontend.rule=Host:www.timothy.de;timothy.de
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - internal
      - proxy
